  server:
   port: 8088
  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
# prefix api like api/v1/user we can set with this api not instead @RequestMapping("api/v1/user")
  api:
    prefix: api/v1